services:

  mysql_db:
    container_name: mysql_db
    build:
      context: .
      dockerfile: mysql.Dockerfile
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sg_attractions
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/data/mysql
    networks:
      - rojak_network
    restart: always

  model:
    container_name: model
    build:
      context: .
      dockerfile: model.Dockerfile
    volumes:
      - model_data:/app/data
    networks:
      - rojak_network

  app:
    container_name: app
    build:
      context: ../Front-End/
      dockerfile: app.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - model_data:/app/data
    networks:
      - rojak_network
    restart: always

volumes:
  mysql_data:
    driver: local
  model_data:
    driver: local

networks:
  rojak_network:
    driver: bridge